import type { AppSnapshot } from './types'

export const mockSnapshot: AppSnapshot = {
  importState: {
    reportMode: 'clinical',
    groupingMode: 'subject_timepoint',
    files: [
      'S01_000a.pdf',
      'S01_001a.pdf',
      'S02_000a.pdf',
      'S02_001a.pdf',
      'S03_000a.pdf',
    ],
    outputPath: 'C:\\Users\\Thoma\\Downloads\\PWA Export (05-08-26 09-10).xlsx',
    greenMax: 3,
    yellowMax: 6,
    pairAlertThreshold: 5,
  },
  summary: {
    processedFiles: 24,
    reviewPatients: 4,
    averagedPatients: 9,
    specialRows: 2,
  },
  reviewPatients: [
    {
      id: '01_000',
      reason: 'pair_alert',
      selectedCount: 2,
      approved: false,
      selectedFiles: ['S01_000a.pdf', 'S01_000b.pdf'],
      currentPairDiffs: {
        sys: 8,
        dia: 6,
        map: 7,
        aorticSys: 5,
        aorticDia: 4,
      },
      rows: [
        {
          keep: true,
          sys: 116,
          dia: 70,
          map: 85,
          aorticSys: 102,
          aorticDia: 70,
          sourceFile: 'S01_000a.pdf',
          pairMethod: 'Auto',
        },
        {
          keep: true,
          sys: 124,
          dia: 76,
          map: 92,
          aorticSys: 107,
          aorticDia: 74,
          sourceFile: 'S01_000b.pdf',
          pairMethod: 'Auto',
        },
      ],
    },
    {
      id: '02_000',
      reason: 'multi_entry',
      selectedCount: 2,
      approved: true,
      selectedFiles: ['S02_000a.pdf', 'S02_000c.pdf'],
      currentPairDiffs: {
        sys: 1,
        dia: 1,
        map: 1,
        aorticSys: 2,
        aorticDia: 1,
      },
      rows: [
        {
          keep: true,
          sys: 111,
          dia: 71,
          map: 84,
          aorticSys: 101,
          aorticDia: 68,
          sourceFile: 'S02_000a.pdf',
          pairMethod: 'Auto',
        },
        {
          keep: false,
          sys: 115,
          dia: 74,
          map: 88,
          aorticSys: 105,
          aorticDia: 70,
          sourceFile: 'S02_000b.pdf',
          pairMethod: 'Manual',
        },
        {
          keep: true,
          sys: 112,
          dia: 72,
          map: 85,
          aorticSys: 103,
          aorticDia: 69,
          sourceFile: 'S02_000c.pdf',
          pairMethod: 'Auto',
        },
      ],
    },
    {
      id: '03_001',
      reason: 'multi_entry_pair_alert',
      selectedCount: 2,
      approved: false,
      selectedFiles: ['S03_001a.pdf', 'S03_001c.pdf'],
      currentPairDiffs: {
        sys: 6,
        dia: 5,
        map: 6,
        aorticSys: 7,
        aorticDia: 5,
      },
      rows: [
        {
          keep: true,
          sys: 118,
          dia: 74,
          map: 89,
          aorticSys: 108,
          aorticDia: 73,
          sourceFile: 'S03_001a.pdf',
          pairMethod: 'Manual',
        },
        {
          keep: false,
          sys: 111,
          dia: 69,
          map: 83,
          aorticSys: 100,
          aorticDia: 67,
          sourceFile: 'S03_001b.pdf',
          pairMethod: 'Auto',
        },
        {
          keep: true,
          sys: 124,
          dia: 79,
          map: 94,
          aorticSys: 115,
          aorticDia: 78,
          sourceFile: 'S03_001c.pdf',
          pairMethod: 'Manual',
        },
      ],
    },
  ],
}
